// Code generated by protoc-gen-go. DO NOT EDIT.
// source: phonebook.proto

package phonebook

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type GetListRequest struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	PhoneNumber          string   `protobuf:"bytes,2,opt,name=phone_number,json=phoneNumber,proto3" json:"phone_number,omitempty"`
	RegencyId            int64    `protobuf:"varint,3,opt,name=regency_id,json=regencyId,proto3" json:"regency_id,omitempty"`
	DistrictId           int64    `protobuf:"varint,4,opt,name=district_id,json=districtId,proto3" json:"district_id,omitempty"`
	VillageId            int64    `protobuf:"varint,5,opt,name=village_id,json=villageId,proto3" json:"village_id,omitempty"`
	Status               int64    `protobuf:"varint,6,opt,name=status,proto3" json:"status,omitempty"`
	Limit                int64    `protobuf:"varint,7,opt,name=limit,proto3" json:"limit,omitempty"`
	Page                 int64    `protobuf:"varint,8,opt,name=page,proto3" json:"page,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetListRequest) Reset()         { *m = GetListRequest{} }
func (m *GetListRequest) String() string { return proto.CompactTextString(m) }
func (*GetListRequest) ProtoMessage()    {}
func (*GetListRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_34db5399df65ad55, []int{0}
}

func (m *GetListRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetListRequest.Unmarshal(m, b)
}
func (m *GetListRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetListRequest.Marshal(b, m, deterministic)
}
func (m *GetListRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetListRequest.Merge(m, src)
}
func (m *GetListRequest) XXX_Size() int {
	return xxx_messageInfo_GetListRequest.Size(m)
}
func (m *GetListRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetListRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetListRequest proto.InternalMessageInfo

func (m *GetListRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *GetListRequest) GetPhoneNumber() string {
	if m != nil {
		return m.PhoneNumber
	}
	return ""
}

func (m *GetListRequest) GetRegencyId() int64 {
	if m != nil {
		return m.RegencyId
	}
	return 0
}

func (m *GetListRequest) GetDistrictId() int64 {
	if m != nil {
		return m.DistrictId
	}
	return 0
}

func (m *GetListRequest) GetVillageId() int64 {
	if m != nil {
		return m.VillageId
	}
	return 0
}

func (m *GetListRequest) GetStatus() int64 {
	if m != nil {
		return m.Status
	}
	return 0
}

func (m *GetListRequest) GetLimit() int64 {
	if m != nil {
		return m.Limit
	}
	return 0
}

func (m *GetListRequest) GetPage() int64 {
	if m != nil {
		return m.Page
	}
	return 0
}

type GetListResponse struct {
	Data                 []*PhoneBook `protobuf:"bytes,1,rep,name=data,proto3" json:"data,omitempty"`
	Metadata             *Metadata    `protobuf:"bytes,2,opt,name=metadata,proto3" json:"metadata,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *GetListResponse) Reset()         { *m = GetListResponse{} }
func (m *GetListResponse) String() string { return proto.CompactTextString(m) }
func (*GetListResponse) ProtoMessage()    {}
func (*GetListResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_34db5399df65ad55, []int{1}
}

func (m *GetListResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetListResponse.Unmarshal(m, b)
}
func (m *GetListResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetListResponse.Marshal(b, m, deterministic)
}
func (m *GetListResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetListResponse.Merge(m, src)
}
func (m *GetListResponse) XXX_Size() int {
	return xxx_messageInfo_GetListResponse.Size(m)
}
func (m *GetListResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetListResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetListResponse proto.InternalMessageInfo

func (m *GetListResponse) GetData() []*PhoneBook {
	if m != nil {
		return m.Data
	}
	return nil
}

func (m *GetListResponse) GetMetadata() *Metadata {
	if m != nil {
		return m.Metadata
	}
	return nil
}

type Metadata struct {
	Page                 int64    `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`
	Total                int64    `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Metadata) Reset()         { *m = Metadata{} }
func (m *Metadata) String() string { return proto.CompactTextString(m) }
func (*Metadata) ProtoMessage()    {}
func (*Metadata) Descriptor() ([]byte, []int) {
	return fileDescriptor_34db5399df65ad55, []int{2}
}

func (m *Metadata) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Metadata.Unmarshal(m, b)
}
func (m *Metadata) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Metadata.Marshal(b, m, deterministic)
}
func (m *Metadata) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Metadata.Merge(m, src)
}
func (m *Metadata) XXX_Size() int {
	return xxx_messageInfo_Metadata.Size(m)
}
func (m *Metadata) XXX_DiscardUnknown() {
	xxx_messageInfo_Metadata.DiscardUnknown(m)
}

var xxx_messageInfo_Metadata proto.InternalMessageInfo

func (m *Metadata) GetPage() int64 {
	if m != nil {
		return m.Page
	}
	return 0
}

func (m *Metadata) GetTotal() int64 {
	if m != nil {
		return m.Total
	}
	return 0
}

type PhoneBook struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	PhoneNumber          string   `protobuf:"bytes,2,opt,name=phone_number,json=phoneNumber,proto3" json:"phone_number,omitempty"`
	Description          string   `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Name                 string   `protobuf:"bytes,4,opt,name=name,proto3" json:"name,omitempty"`
	Address              string   `protobuf:"bytes,5,opt,name=address,proto3" json:"address,omitempty"`
	RegencyId            int64    `protobuf:"varint,6,opt,name=regency_id,json=regencyId,proto3" json:"regency_id,omitempty"`
	DistrictId           int64    `protobuf:"varint,7,opt,name=district_id,json=districtId,proto3" json:"district_id,omitempty"`
	VillageId            int64    `protobuf:"varint,8,opt,name=village_id,json=villageId,proto3" json:"village_id,omitempty"`
	Latitude             string   `protobuf:"bytes,9,opt,name=latitude,proto3" json:"latitude,omitempty"`
	Longitude            string   `protobuf:"bytes,10,opt,name=longitude,proto3" json:"longitude,omitempty"`
	CoverImagePath       string   `protobuf:"bytes,11,opt,name=cover_image_path,json=coverImagePath,proto3" json:"cover_image_path,omitempty"`
	Status               int64    `protobuf:"varint,12,opt,name=status,proto3" json:"status,omitempty"`
	CreatedAt            string   `protobuf:"bytes,13,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt            string   `protobuf:"bytes,14,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	CategoryId           int64    `protobuf:"varint,15,opt,name=category_id,json=categoryId,proto3" json:"category_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PhoneBook) Reset()         { *m = PhoneBook{} }
func (m *PhoneBook) String() string { return proto.CompactTextString(m) }
func (*PhoneBook) ProtoMessage()    {}
func (*PhoneBook) Descriptor() ([]byte, []int) {
	return fileDescriptor_34db5399df65ad55, []int{3}
}

func (m *PhoneBook) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PhoneBook.Unmarshal(m, b)
}
func (m *PhoneBook) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PhoneBook.Marshal(b, m, deterministic)
}
func (m *PhoneBook) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PhoneBook.Merge(m, src)
}
func (m *PhoneBook) XXX_Size() int {
	return xxx_messageInfo_PhoneBook.Size(m)
}
func (m *PhoneBook) XXX_DiscardUnknown() {
	xxx_messageInfo_PhoneBook.DiscardUnknown(m)
}

var xxx_messageInfo_PhoneBook proto.InternalMessageInfo

func (m *PhoneBook) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *PhoneBook) GetPhoneNumber() string {
	if m != nil {
		return m.PhoneNumber
	}
	return ""
}

func (m *PhoneBook) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *PhoneBook) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *PhoneBook) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

func (m *PhoneBook) GetRegencyId() int64 {
	if m != nil {
		return m.RegencyId
	}
	return 0
}

func (m *PhoneBook) GetDistrictId() int64 {
	if m != nil {
		return m.DistrictId
	}
	return 0
}

func (m *PhoneBook) GetVillageId() int64 {
	if m != nil {
		return m.VillageId
	}
	return 0
}

func (m *PhoneBook) GetLatitude() string {
	if m != nil {
		return m.Latitude
	}
	return ""
}

func (m *PhoneBook) GetLongitude() string {
	if m != nil {
		return m.Longitude
	}
	return ""
}

func (m *PhoneBook) GetCoverImagePath() string {
	if m != nil {
		return m.CoverImagePath
	}
	return ""
}

func (m *PhoneBook) GetStatus() int64 {
	if m != nil {
		return m.Status
	}
	return 0
}

func (m *PhoneBook) GetCreatedAt() string {
	if m != nil {
		return m.CreatedAt
	}
	return ""
}

func (m *PhoneBook) GetUpdatedAt() string {
	if m != nil {
		return m.UpdatedAt
	}
	return ""
}

func (m *PhoneBook) GetCategoryId() int64 {
	if m != nil {
		return m.CategoryId
	}
	return 0
}

func init() {
	proto.RegisterType((*GetListRequest)(nil), "phonebook.GetListRequest")
	proto.RegisterType((*GetListResponse)(nil), "phonebook.GetListResponse")
	proto.RegisterType((*Metadata)(nil), "phonebook.Metadata")
	proto.RegisterType((*PhoneBook)(nil), "phonebook.PhoneBook")
}

func init() { proto.RegisterFile("phonebook.proto", fileDescriptor_34db5399df65ad55) }

var fileDescriptor_34db5399df65ad55 = []byte{
	// 480 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x93, 0xcf, 0x6e, 0x13, 0x31,
	0x10, 0xc6, 0xb5, 0x49, 0x9a, 0x64, 0x67, 0x4b, 0x52, 0x99, 0x0a, 0x99, 0x88, 0x8a, 0x90, 0x53,
	0x4e, 0x45, 0x0a, 0x3c, 0x00, 0xe5, 0x02, 0x91, 0x00, 0x55, 0x2b, 0xee, 0x91, 0xb3, 0x1e, 0x25,
	0x56, 0x37, 0xeb, 0xc5, 0x9e, 0x54, 0xe2, 0x0d, 0x79, 0x14, 0x1e, 0x03, 0x79, 0xf6, 0x4f, 0xb6,
	0x15, 0x52, 0x7b, 0xf3, 0xfc, 0xbe, 0x19, 0xdb, 0xe3, 0x6f, 0x0c, 0xd3, 0x72, 0x6f, 0x0b, 0xdc,
	0x5a, 0x7b, 0x77, 0x5d, 0x3a, 0x4b, 0x56, 0xc4, 0x2d, 0x58, 0xfc, 0x8d, 0x60, 0xf2, 0x05, 0xe9,
	0x9b, 0xf1, 0x94, 0xe2, 0xaf, 0x23, 0x7a, 0x12, 0x02, 0x06, 0x85, 0x3a, 0xa0, 0x8c, 0xe6, 0xd1,
	0x32, 0x4e, 0x79, 0x2d, 0xde, 0xc1, 0x39, 0xd7, 0x6c, 0x8a, 0xe3, 0x61, 0x8b, 0x4e, 0xf6, 0x58,
	0x4b, 0x98, 0xfd, 0x60, 0x24, 0xae, 0x00, 0x1c, 0xee, 0xb0, 0xc8, 0x7e, 0x6f, 0x8c, 0x96, 0xfd,
	0x79, 0xb4, 0xec, 0xa7, 0x71, 0x4d, 0xd6, 0x5a, 0xbc, 0x85, 0x44, 0x1b, 0x4f, 0xce, 0x64, 0x14,
	0xf4, 0x01, 0xeb, 0xd0, 0xa0, 0xb5, 0x0e, 0xf5, 0xf7, 0x26, 0xcf, 0xd5, 0x0e, 0x83, 0x7e, 0x56,
	0xd5, 0xd7, 0x64, 0xad, 0xc5, 0x2b, 0x18, 0x7a, 0x52, 0x74, 0xf4, 0x72, 0xc8, 0x52, 0x1d, 0x89,
	0x4b, 0x38, 0xcb, 0xcd, 0xc1, 0x90, 0x1c, 0x31, 0xae, 0x82, 0xd0, 0x43, 0xa9, 0x76, 0x28, 0xc7,
	0x0c, 0x79, 0xbd, 0xc8, 0x61, 0xda, 0x76, 0xea, 0x4b, 0x5b, 0x78, 0x14, 0x4b, 0x18, 0x68, 0x45,
	0x4a, 0x46, 0xf3, 0xfe, 0x32, 0x59, 0x5d, 0x5e, 0x9f, 0x1e, 0xea, 0x36, 0xac, 0x3e, 0x5b, 0x7b,
	0x97, 0x72, 0x86, 0x78, 0x0f, 0xe3, 0x03, 0x92, 0xe2, 0xec, 0xd0, 0x7c, 0xb2, 0x7a, 0xd9, 0xc9,
	0xfe, 0x5e, 0x4b, 0x69, 0x9b, 0xb4, 0xf8, 0x08, 0xe3, 0x86, 0xb6, 0xb7, 0x89, 0x4e, 0xb7, 0x09,
	0xf7, 0x26, 0x4b, 0x2a, 0xe7, 0xdd, 0xfa, 0x69, 0x15, 0x2c, 0xfe, 0xf4, 0x21, 0x6e, 0x8f, 0x16,
	0x13, 0xe8, 0x19, 0x5d, 0x57, 0xf5, 0x8c, 0x7e, 0x8e, 0x0b, 0x73, 0x48, 0x34, 0xfa, 0xcc, 0x99,
	0x92, 0x8c, 0x2d, 0xd8, 0x86, 0x38, 0xed, 0xa2, 0xd6, 0xde, 0x41, 0xc7, 0x5e, 0x09, 0x23, 0xa5,
	0xb5, 0x43, 0xef, 0xf9, 0xe1, 0xe3, 0xb4, 0x09, 0x1f, 0xb9, 0x3a, 0x7c, 0xc2, 0xd5, 0xd1, 0x13,
	0xae, 0x8e, 0x1f, 0xbb, 0x3a, 0x83, 0x71, 0xae, 0xc8, 0xd0, 0x51, 0xa3, 0x8c, 0xf9, 0xe4, 0x36,
	0x16, 0x6f, 0x20, 0xce, 0x6d, 0xb1, 0xab, 0x44, 0x60, 0xf1, 0x04, 0xc4, 0x12, 0x2e, 0x32, 0x7b,
	0x8f, 0x6e, 0x63, 0x0e, 0x61, 0xf3, 0x52, 0xd1, 0x5e, 0x26, 0x9c, 0x34, 0x61, 0xbe, 0x0e, 0xf8,
	0x56, 0xd1, 0xbe, 0x33, 0x39, 0xe7, 0x0f, 0x26, 0xe7, 0x0a, 0x20, 0x73, 0xa8, 0x08, 0xf5, 0x46,
	0x91, 0x7c, 0x51, 0x1d, 0x50, 0x93, 0x1b, 0x0a, 0xf2, 0xb1, 0xd4, 0x8d, 0x3c, 0xa9, 0xe4, 0x9a,
	0xdc, 0x50, 0xe8, 0x3c, 0x53, 0x84, 0x3b, 0xeb, 0xf8, 0x65, 0xa6, 0x55, 0xe7, 0x0d, 0x5a, 0xeb,
	0xd5, 0x4f, 0xb8, 0x68, 0x9d, 0xfc, 0xaa, 0x0a, 0x9d, 0xa3, 0x13, 0x9f, 0x60, 0x54, 0x8f, 0xa0,
	0x78, 0xdd, 0x19, 0x9f, 0x87, 0x1f, 0x70, 0x36, 0xfb, 0x9f, 0x54, 0x4d, 0xec, 0x76, 0xc8, 0x3f,
	0xf8, 0xc3, 0xbf, 0x00, 0x00, 0x00, 0xff, 0xff, 0x18, 0xd8, 0x8a, 0x49, 0xd4, 0x03, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// PhoneBookHandlerClient is the client API for PhoneBookHandler service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type PhoneBookHandlerClient interface {
	GetList(ctx context.Context, in *GetListRequest, opts ...grpc.CallOption) (*GetListResponse, error)
}

type phoneBookHandlerClient struct {
	cc *grpc.ClientConn
}

func NewPhoneBookHandlerClient(cc *grpc.ClientConn) PhoneBookHandlerClient {
	return &phoneBookHandlerClient{cc}
}

func (c *phoneBookHandlerClient) GetList(ctx context.Context, in *GetListRequest, opts ...grpc.CallOption) (*GetListResponse, error) {
	out := new(GetListResponse)
	err := c.cc.Invoke(ctx, "/phonebook.PhoneBookHandler/GetList", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PhoneBookHandlerServer is the server API for PhoneBookHandler service.
type PhoneBookHandlerServer interface {
	GetList(context.Context, *GetListRequest) (*GetListResponse, error)
}

// UnimplementedPhoneBookHandlerServer can be embedded to have forward compatible implementations.
type UnimplementedPhoneBookHandlerServer struct {
}

func (*UnimplementedPhoneBookHandlerServer) GetList(ctx context.Context, req *GetListRequest) (*GetListResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetList not implemented")
}

func RegisterPhoneBookHandlerServer(s *grpc.Server, srv PhoneBookHandlerServer) {
	s.RegisterService(&_PhoneBookHandler_serviceDesc, srv)
}

func _PhoneBookHandler_GetList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PhoneBookHandlerServer).GetList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/phonebook.PhoneBookHandler/GetList",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PhoneBookHandlerServer).GetList(ctx, req.(*GetListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _PhoneBookHandler_serviceDesc = grpc.ServiceDesc{
	ServiceName: "phonebook.PhoneBookHandler",
	HandlerType: (*PhoneBookHandlerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetList",
			Handler:    _PhoneBookHandler_GetList_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "phonebook.proto",
}
